# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2dc937f2b21313215d2dd1badcb4290633b895a46473f1836a9b114d0872ae4b70e1ada3b3cbf3891920761cb9ba121f863709c9359711de054d4eb22dee747

test:
  secret_key_base: 562586a82790b87b2685adff90aab4637c73a761f730d897c0f83678be54a5be621ca587d9fe68855cc3ea1ba6f1fe5fa609cf831371138337f8be9d419ac1bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
